SELECT * FROM tblCustomerType;

DECLARE @NUM_CUST INT = (SELECT COUNT(*) FROM tblCustomer);

DECLARE @ROW_COUNT INT = @NUM_CUST

DECLARE @MIN_CUST_ID INT = (SELECT MIN(CustomerID) FROM tblCustomer);

DECLARE @NUM_CUST_TYPES INT = (SELECT COUNT(*) FROM tblCustomerType);

DECLARE @MIN_CUST_TYPE_ID INT = (SELECT MIN(CustTypeID) FROM tblCustomerType);

WHILE @ROW_COUNT > 0
BEGIN
	DECLARE @CUST_TYPES INT = (SELECT RAND()*3)+1;

	PRINT @CUST_TYPES

	DECLARE @CUST_ID INT= (SELECT RAND()*@NUM_CUST+@MIN_CUST_ID)

	PRINT 'Cust ID' + CAST(@CUST_ID as varchar(50))

	WHILE NOT EXISTS(SELECT CustomerID FROM tblCustomer WHERE CustomerID = @CUST_ID)
	BEGIN	
		SET @CUST_ID = (SELECT RAND()*@ROW_COUNT)
	END

	PRINT @CUST_ID 

	WHILE @CUST_TYPES > 0
	BEGIN
		DECLARE @CUST_TYPE INT = (SELECT RAND()*@NUM_CUST_TYPES+@MIN_CUST_TYPE_ID)
		WHILE NOT EXISTS (SELECT * FROM tblCustomerType WHERE CustTypeID = @CUST_TYPE) 
			BEGIN
				SET @CUST_TYPE = (SELECT RAND()*@NUM_CUST_TYPES+@MIN_CUST_TYPE_ID);
			END

		DECLARE @CUSTOMER_TYPE_STR varchar(50) = (SELECT CustTypeName FROM tblCustomerType WHERE CustTypeID = @CUST_TYPE);

		EXEC emilyd61_uspGetCustTypeID @CustTypeName = @CUSTOMER_TYPE_STR, @CustTypeDescr=NULL, @CustTID = @CUST_TYPE OUTPUT

		INSERT INTO tblCustomerCustomerType (CustomerID, CustTypeID, StartDate) VALUES (@CUST_ID, @CUST_TYPE, GetDate())
		
		SET @CUST_TYPES = @CUST_TYPES -1;
	END
	
	SET @ROW_COUNT = @ROW_COUNT -1;
 
END

SELECT * FROM tblCustomerCustomerType